export const SUBMIT_CONTACT_FORM = 'SUBMIT_CONTACT_FORM';
export const GET_CONTACTS = 'GET_CONTACTS';
export const DELETE_CONTACTS = 'DELETE_CONTACTS';
export const CHOOSE_LANGUAGE = "CHOOSE_LANGUAGE";
